Blog App -validations and model specs.
Harrynoqs/blog_app pull request #3
Opened 2023-01-27 16:15 UTC by Harrynoqs

For the User model:
Name must not be blank.
PostsCounter must be an integer greater than or equal to zero.
For the Post model:
Title must not be blank.

CommentsCounter must be an integer greater than or equal to zero.

LikesCounter must be an integer greater than or equal to zero.

Add unit specs for all of your models' methods and validations.

2023-01-27 17:24 UTC, BertrandConxy requested changes
Hi @Harrynoqs, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 


## Highlights 💪 
- No linter errors
- correct flow is used
- good PR


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-27 17:24 UTC, BertrandConxy commented on app/models/user.rb
> +  validates :PostCounter, numericality: { greater_than_or_equal_to: 0 }
- [ ] [OPTIONAL] I would suggest that you put all your validations on the top of file so that they will be checked before any thing else 😃 👍

2023-01-27 17:24 UTC, BertrandConxy commented on app/models/user.rb
> +  end
- [ ] Good job so far 👏 👏 Your tests look good. In addition to what you have done, I would suggest adding tests for the following custom method in the `User` model that helps you query the latest post. This is among the project requirements as you can see below 👇 
![image](https://user-images.githubusercontent.com/90222110/215150348-f0480b20-1691-49f6-9221-0ec92639b89a.png)

2023-01-27 17:24 UTC, BertrandConxy commented on app/models/post.rb
> +  end
- [ ] Good job so far 👏 👏. In addition to what you have done, I would suggest adding tests for the following custom method in the `Post` model that helps you query the latest comments on a post 😃 👍 . This is among the project requirements as you can see below 👇 
![image](https://user-images.githubusercontent.com/90222110/215150862-cff865e0-9365-4efa-ae55-eb4a54349a80.png)

2023-01-28 08:35 UTC, mwanawabangona requested changes
Hi @Harrynoqs ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has `linter errors`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-28 09:19 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Harrynoqs👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 09:19 UTC, thecodechaser commented on spec/models/user_spec.rb
> +end
- [ ] As requested by the previous reviewer, Please add a test for the custom method available in the User model `latest_posts`. This test should check 3 recent posts for a user.

2023-01-28 09:19 UTC, thecodechaser commented on spec/models/post_spec.rb
> +end
- [ ] As requested by the previous reviewer, Please add a test for the custom method available in the Post model `latest_comments`. This test should check 5 recent comments for a post.

2023-01-28 16:08 UTC, KDlamini approved these changes
### Hi @Harrynoqs 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ Great PR title and description
✔️ Model validation specs are present
✔️ No linter errors

# Status: Approved ✔️ 

![simon](https://user-images.githubusercontent.com/38088818/215275405-1ee5e876-e5f3-41e4-bf7f-7ce9b6ba7f51.gif)

## Optional suggestions💡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 16:08 UTC, KDlamini commented on README.md
> +Modify this file to match your project and remove sections that don't apply.
**NOTE:** The optional points are only optional because they were not mentioned by the previous reviewer, but I highly recommend that you take them into consideration.

There are a few things you can improve about your README to make it more professional.

## [OPTIONAL] 

- The `Show your support` section is not documented. Kindly write the relevant information for this section.

![image](https://user-images.githubusercontent.com/38088818/215269420-b75df450-36fe-4d5f-960c-81f14790bf78.png)

- Surely there's someone you can acknowledge that helped you complete this project whether it's your coding partner(s), the Morning session team for motivation, or the Microverse team for the great curriculum.

![image](https://user-images.githubusercontent.com/38088818/215272422-8aa47b7b-3aa0-444a-ba89-65e87046fda2.png)

- Please make sure that you do not have any broken links on your README. The link to your license is broken, kindly fix it and make sure that users are redirected to the relevant license file.

![image](https://user-images.githubusercontent.com/38088818/215269620-db659080-3d05-4f03-b565-ee474d1432ee.png)


- Kindly remove all the description texts under each section that came with the template, they are meant to guide you on how to modify each section. They should not be in the final documentation of your project.

For example:
![image](https://user-images.githubusercontent.com/38088818/215275691-6b7906c4-fee9-41fc-8618-ade8e3679df8.png)
![image](https://user-images.githubusercontent.com/38088818/215275732-1f63b285-1a03-47ac-b0e6-522b1e6ca605.png)
![image](https://user-images.githubusercontent.com/38088818/215269075-92a07196-0c26-4b46-91ac-bacaf8edf3f6.png)

And so forth... Be sure to remove the rest that is not included in the screenshots above.

- Please add the relevant information under the `Getting Started` sub-sections like `Setup`, `install`, `Usage`, `Run Tests`, and `Deployment`. if there's no information yet leave a `none` text. These sub-sections should explain how to clone the repo and how to run it locally. Since this milestone is about testing, the `Run tests` section should have the right command on how to run the tests.

2023-01-31 08:16 UTC, merged